[env:s3-zero]
platform = espressif32@^6.5.0
board = esp32-s3-devkitm-1
framework = arduino
board_build.flash_size = 4MB
board_build.partitions = partitions_test.csv
board_build.filesystem = littlefs
monitor_speed = 115200

lib_deps =
    h2zero/NimBLE-Arduino@^1.4.0
    knolleary/PubSubClient@^2.8

lib_ldf_mode = deep+

build_flags =
    -I../shared
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_PM_ENABLE
    -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL=0
    -DCONFIG_BT_NIMBLE_ROLE_BROADCASTER
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL=0
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER=0
